"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _hero_section from './hero-section.bones.json'
import _blog_index from './blog-index.bones.json'
import _projects_grid from './projects-grid.bones.json'

configureBoneyard({"color":"#313227","darkColor":"#22241d","animate":"shimmer","shimmerColor":"#494b3b","darkShimmerColor":"#313227","speed":"1.8s","shimmerAngle":110,"transition":200})

registerBones({
  "hero-section": _hero_section,
  "blog-index": _blog_index,
  "projects-grid": _projects_grid,
})
